### ISSUE TITLE
not an issue but just wondering how you did the renders used in the readme

### ISSUE THREAD

**Issue by arceuss** [Pete-Lawrence/Peters-Noteskins#1]

**Comment by Pete-Lawrence** [comment]
I rendered them out in Blender and used GIMP to convert the PNGs into a GIF animation.

**Comment by arceuss** [comment]
> I rendered them out in Blender and used GIMP to convert the PNGs into a GIF animation.

how did you do animated textures in blender then

**Comment by arceuss** [comment]
> I rendered them out in Blender and used GIMP to convert the PNGs into a GIF animation.

how did you render them in blender, when i try it looks offcentered and weird

**Comment by Pete-Lawrence** [comment]
.
